openapi: 3.0.0
info: 
  title: Api Portifólio Danilo Scipioni
  version: 1.0.1
  contact: 
    name: Danilo Eduardo Scipioni
    email: daniloedu@gmail.com
    url: https://github.com/daniloscipioni
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes onlys
  schemas:
    Login:
      type: object
      properties:
        user:
          type: string
        password:
          type: string
      example:
            user: daniloscipioni
            password: danilo89
    Users:
      type: object
      properties:
        id_user:
          type: integer
    Register:
      type: object
      properties:
      example:
            username: daniloscipioni
            password: danilo89
            email: daniloedu@gmail.com
    Update:
      type: integer
      properties:
         category:
          type: integer
          example: 1
    Rss:
      type: object
      properties:
        title:
          type: string
        content: 
          type: string
        link: 
          type: string
        date: 
          type: date
        categories: 
          type: array
      example:
            title": A New System Is Helping Crack Down on Child Sex Abuse Images
            content": There are 150 child sexual abuse laws around the world. Now, metadata is making it easier for countries to work together.
            link": https://www.wired.com/story/new-system-crack-down-child-sex-abuse-images
            date": 10/07/2021 10:00:00
            categories": ["Security","Security / Security News"] 
    
    
